spring.application.name=SpringBoot06

my-prefix.id=1001
my-prefix.email=123456@qq.com
my-prefix.age=20

customer.info.name=John
customer.info.age=22
customer.info.address.city=Shanghai
customer.info.address.street=Minhang

student.info.student-array2[0].name="Susan"
student.info.student-array2[0].age=31
student.info.student-array2[1].name="Smith"
student.info.student-array2[1].age=32