# Spring Boot脚手架自动生成的
spring.application.name=SpringBoot07

spring.config.import=classpath:application-mysql.properties,classpath:application-mybatis.properties,classpath:application-redis.properties
