# mybatis相关配置
# 告诉MyBatis框架MapperXML文件的位置
# 指定mapper映射文件路径，SqlMapper.xml文件的存放路径和Mapper接口在同一个目录下，则不需要指定该配置
mybatis.mapper-locations=classpath:mapper/*.xml
# 下划线转驼峰 自动把数据库字段 vip_name 映射到实体类属性 vipName ，不用手动写as vipName
mybatis.configuration.map-underscore-to-camel-case=true
# 起别名 给entity包下所有实体类设置别名，xml文件里可以直接写Vip代替com.wyjun.entity.Vip
mybatis.type-aliases-package=com.wyjun.entity
# 打印SQL日志
logging.level.com.wyjun.mapper=DEBUG